Repository Climeeting/climeet-fe, pull requests merged in 2024-06, with the labels that each got.

#22 #15 설문조사 UX
  package.json
  pnpm-lock.yaml
  src/components/RadioButtonGroup.module.scss
  src/components/RadioButtonGroup.tsx
  src/pages/Home/HomePage.tsx
  src/pages/PartySurveyForm/PartySurveyFormPage.module.scss
  src/pages/PartySurveyForm/PartySurveyFormPage.tsx
  src/pages/PartySurveyForm/components/PartyConditionForm.module.scss
  src/pages/PartySurveyForm/components/PartyConditionForm.tsx
  src/pages/PartySurveyForm/components/PartyIntroduceForm.module.scss
  src/pages/PartySurveyForm/components/PartyIntroduceForm.tsx
  src/pages/PartySurveyForm/components/PartyPlaceForm.module.scss
  src/pages/PartySurveyForm/components/PartyPlaceForm.tsx
  src/pages/PartySurveyForm/components/PartyScheduleForm.module.scss
  src/pages/PartySurveyForm/components/PartyScheduleForm.tsx
  src/pages/stackflow.ts
  src/utils/useFunnel.tsx
Labels: feature

#30 #26 절대 경로 설정 & 컬러값 관리
  global.scss
  package.json
  pnpm-lock.yaml
  src/components/Chip.module.scss
  src/components/NavBar/BottomBar.module.scss
  src/components/Search.module.scss
  src/components/Select.module.scss
  src/components/ToggleButton.module.scss
  src/pages/Home/HomePage.module.scss
  src/pages/Home/HomePage.tsx
  src/pages/Home/Profile.tsx
  src/pages/Home/components/FilterBottomSheet.module.scss
  src/pages/Home/components/FilterBottomSheet.tsx
  src/pages/Home/components/FilterButton.module.scss
  src/pages/Home/components/FilterButton.tsx
  src/pages/Home/components/FilterList.tsx
  src/pages/Home/components/PartyCard.tsx
  src/pages/Home/components/Tabs.module.scss
  src/pages/Oauth/OauthPage.tsx
  tsconfig.json
  vite.config.ts
Labels: feature

#34 #33 파티 상세 페이지 마크업
  package.json
  pnpm-lock.yaml
  src/components/Avatar.module.scss
  src/components/Avatar.tsx
  src/components/Chip.tsx
  src/components/Icon/svgs/calendar_line.svg
  src/components/Icon/svgs/index.ts
  src/components/Icon/svgs/person_line.svg
  src/components/Icon/svgs/type_line.svg
  src/pages/Home/HomePage.tsx
  src/pages/PartyDetailPage/PartyDetailPage.module.scss
  src/pages/PartyDetailPage/PartyDetailPage.tsx
  src/pages/PartyDetailPage/components/PartyClimbInfo.module.scss
  src/pages/PartyDetailPage/components/PartyClimbInfo.tsx
  src/pages/PartyDetailPage/components/PartyDescription.module.scss
  src/pages/PartyDetailPage/components/PartyDescription.tsx
  src/pages/PartyDetailPage/components/PartyMainInfo.module.scss
  src/pages/PartyDetailPage/components/PartyMainInfo.tsx
  src/pages/PartyDetailPage/components/PartyParticipants.module.scss
  src/pages/PartyDetailPage/components/PartyParticipants.tsx
  src/pages/stackflow.ts
Labels: feature

#44 #43 eslint: react-refresh/only-export-components 에러 해결
  .eslintrc.cjs
Labels: bug

#51 #36 DatePicker
  package.json
  pnpm-lock.yaml
  src/components/DatePicker.module.scss
  src/components/DatePicker.tsx
  src/main.tsx
  src/pages/Home/HomePage.tsx
  src/utils/dayjs.ts
Labels: feature

#54 #53 모바일 최적화
  index.html
Labels: feature

#56 #55 stackflow 걷어내고 router 적용하기
  package.json
  src/components/Icon/svgs/arrow_left.svg
  src/components/Icon/svgs/index.ts
  src/components/NavBar/BottomBar.tsx
  src/components/NavBar/TopBar.module.scss
  src/components/NavBar/TopBar.tsx
  src/main.tsx
  src/pages/Home/HomePage.module.scss
  src/pages/Home/HomePage.tsx
  src/pages/Layout/Layout.tsx
  src/pages/Login/LoginPage.module.scss
  src/pages/Login/LoginPage.tsx
  src/pages/Modal.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/Oauth/OauthPage.tsx
  src/pages/PartyDetailPage/PartyDetailPage.module.scss
  src/pages/PartyDetailPage/PartyDetailPage.tsx
  src/pages/PartySurveyForm/PartySurveyFormPage.module.scss
  src/pages/PartySurveyForm/PartySurveyFormPage.tsx
  src/pages/routes.tsx
  src/reset.css
Labels: refactor

#58 #57 폰트 스타일 적용
  global.scss
Labels: style

#64 #52 홈화면 api 연결
  package.json
  pnpm-lock.yaml
  src/components/BottomSheet.tsx
  src/components/DatePicker.tsx
  src/components/NavBar/BottomBar.tsx
  src/pages/Home/HomePage.tsx
  src/pages/Home/components/FilterBottomSheet.tsx
  src/pages/Home/components/FilterList.tsx
  src/pages/Home/components/PartyCard.module.scss
  src/pages/Home/components/PartyCard.tsx
  src/pages/Home/components/PartyList.module.scss
  src/pages/Home/components/PartyList.tsx
  src/pages/Home/hooks/useDateContext.tsx
  src/pages/Home/hooks/useFilterContext.tsx
  src/pages/types/api.ts
  src/services/party.ts
  src/utils/dayjs.ts
  src/utils/useLoadMore.tsx
Labels: feature

#72 #66 유저 추가 정보 입력 페이지
  package.json
  pnpm-lock.yaml
  src/pages/MyInfoFormPage/MyInfoFormPage.module.scss
  src/pages/MyInfoFormPage/MyInfoFormPage.tsx
  src/pages/MyInfoFormPage/components/ToggleSex.module.scss
  src/pages/MyInfoFormPage/components/ToggleSex.tsx
  src/pages/routes.tsx
  src/pages/types/api.ts
  src/reset.css
  src/services/party.ts
  src/services/user.ts
Labels: feature

#73 #65 파티 디테일 페이지
  src/pages/Home/components/PartyCard.tsx
  src/pages/PartyDetailPage/PartyDetailPage.tsx
  src/pages/PartyDetailPage/components/PartyDescription.module.scss
  src/pages/PartyDetailPage/components/PartyDescription.tsx
  src/pages/PartyDetailPage/components/PartyDetail.tsx
  src/pages/PartyDetailPage/components/PartyMainInfo.tsx
  src/pages/PartyDetailPage/components/PartyParticipants.module.scss
  src/pages/PartyDetailPage/components/PartyParticipants.tsx
  src/pages/PartySurveyForm/PartySurveyFormPage.tsx
  src/pages/types/api.ts
  src/services/party.ts
  src/services/user.ts
Labels: feature

#75 #74 refactor: 어댑터에서 반복되는 메서드를 함수로 분리하여 재사용
  src/pages/Home/hooks/useFilterContext.tsx
  src/services/adaptor.ts
  src/services/party.ts
  src/services/user.ts
Labels: refactor
